#Makefile

#defaults

SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/../src/top.v $(PWD)/../src/log.v

TOPLEVEL = top

MODULE = testbench

include $(shell cocotb-config --makefile)/Makefile.sim